### ISSUE TITLE
[suggestion] Wrap around after pressing "n" on the bottom window

### ISSUE THREAD

**Issue by alienbogart** [clemera/buffer-expose#1]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
of 2019-02-12
- Evil version 1.2.14
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- buffer-expose-0.1

First of all, thank you very much for this awesome mode.

##### The Issue

When I run `buffer-expose-no-stars`, if I press `n` on the bottom window I get the message `user-error: Minibuffer is inactive`. I wish to have the option to wrap around (go to the top window) instead.

I noticed you're using `Windmove` for that, but I happen to use this package and wish to retain the `(setq windmove-wrap-around nil)` setting when using it outside of `buffer-expose-no-stars`.

**Comment by clemera** [comment]
Thanks for the suggestion. This is now possible using `buffer-expose-wrap-vertically` which is `t` by default.
