### ISSUE TITLE
Evilify?

### ISSUE THREAD

**Issue by mpanarin** [clemera/buffer-expose#2]
Hello! Thanks for this greate package!

I have a few suggestions:
1. Maybe add a list of ignored buffers? So people could easly add some of them to the ignored list
2. Also will you evilify the package? 

Thanks!

**Comment by clemera** [comment]
Hi,

> Maybe add a list of ignored buffers

There already is `buffer-expose-hide-regexes`. 

> will you evilify the package

I don't use evil-mode what would be needed to make it work with it?

**Comment by alienbogart** [comment]
### 1. Here's my `buffer-expose-hide-regexes`. You may find it useful.

```
(setq buffer-expose-hide-regexes '(".*Log.*"
				   ".*log.*"
				   ".*help.*"
				   "^#.*#$"
				   "*Shell Command Output*"
				   "*Calculator*"
				   "*Calendar*"
				   "*Help*"
				   "*Calc Trail*"
				   "magit-process"
				   "magit-diff"
				   "*Org-Babel Error Output*"
				   "\\`\\*helm"
				   "\\`\\*Echo Area"
				   "\\`\\*Minibuf"
				   "Ibuffer"
				   "*Shell Command Output*"
				   "*Calculator*"
				   "*Calendar*"
				   "*cheatsheet*"
				   "*Help*"
				   "*Echo Area 0*"
				   "*Echo Area 1"
				   "*Minibuf 0*"
				   "bookmark-default.el"
				   "info-history"
				   "company-shell-autoloads.el"
				   "company.el"
				   "pos-tip-autoloads.el"
				   "*Warning*"
				   "*Messages*"
				   "*Flycheck error messages*"
				   "*company-documentation*"
				   "^.archive.org$"
				   ".*magit.*"
				   ".*elc"
				   "*shell*"
				   "*new*"
				   "*Flycheck error messages*"
				   "*clang-output*"
				   "*Bongo Playlist*"
				   "*eclim: problems*"
				   "*eclimd*"
				   "*compilation*"))
```

### 2. "Evilifying" 

It's really not that hard. `buffer-expose` doesn't have many keybindings. Here's what I did (using [general)](https://github.com/noctuid/general.el):

```
  (general-define-key
   :keymaps 'buffer-expose-grid-map
   "h" 'buffer-expose-left-window
   "k" 'windmove-up
   "j" 'windmove-down
   "l" 'buffer-expose-right-window
   "m" 'buffer-expose-choose)
```

**Comment by clemera** [comment]
Note that with recent versions you should replace windmove commands like so:

windmove-up > buffer-expose-up-window
windmove-down > buffer-expose-down-window

**Comment by clemera** [comment]
And related to `buffer-expose-hide-regexes` there is the command `buffer-expose-no-stars` which hides \*star\* buffers by default.

**Comment by clemera** [comment]
I consider the issue as closed as it seems it does work with evil-mode only the bindings are not evil like and as I don't want to maintain evil bindings this should be done by personal user config or you may consider adding it to the evil-collection package. Thanks for the suggestions!
