### ISSUE TITLE
defgroup buffer-expose docstring looks wrong

### ISSUE THREAD

**Issue by pcrama** [clemera/buffer-expose#4]
The docstring of `buffer-expose` looks wrong to me:
https://github.com/clemera/buffer-expose/blob/5dd61e4a04fd3e93f10907f0506e1b4dd3b12cf4/buffer-expose.el#L81
I would suggest using `"Visual buffer switching using a window grid"` instead.

**Comment by clemera** [comment]
Ups, thanks!
