### ISSUE TITLE
Feature request: kill highlighted buffer

### ISSUE THREAD

**Issue by tmalsburg** [clemera/buffer-expose#5]
Amazing package, thank you!  It would be great if we could use it not just to select buffers but also for basic management of buffers.  For instance, it would be cool if I could just press `k` to kill the currently highlighted buffer.  Or some other key to save the highlighted buffer, and so on.

**Comment by clemera** [comment]
Thanks for the suggestion! There is an experimental `buffer-expose-kill-buffer` command which is not bound by default, which you can test (I have not tested it for a while but let it there as an reminder to add it at some point). I have to think about which other commands to add. The focus is quickly switching buffers, then after you have switched you can do anything, like save or kill the buffer. But I can see that sometimes it's nice to walk through the buffer overview and apply actions without having to switch to the buffers.

**Comment by tmalsburg** [comment]
Thank you!  It largely works. Three small problems, though:
1. When I `buffer-expose` and try to kill the buffer that is selected by default, nothing happens except that the next buffer is selected.  Killing seems to work only after the selection is changed.
2. If the buffer has unsaved modifications I get asked whether I want to kill anyway. If I say "yes", the buffer is killed and the next buffer is selected.  However, when I say "no" the next buffer is selected as well.  I think it would be nicer if the next buffer was only selected if we actually kill the buffer.
3. When I kill a buffer that has no buffers in the neighboring grid cells, I get stuck and can't move the selection.

I understand that buffer-expose is not meant to be a general buffer management tool, but when I see all those stale buffers, it really really makes me want to clean up, and fast. :)

**Comment by clemera** [comment]
Thanks for the feedback. I have adjusted the code and added the new command to the grid map. I had to change the implementation a bit, empty windows can now be selected. Could you give it some testing?

**Comment by tmalsburg** [comment]
1. and 3. are solved.  Great!  2. is a not optimal yet.  When I try to kill with unsaved changes, the selection first moves foward and then back when I decide not to kill.  This is suboptimal because the user might get confused about which buffer the question in the minibuffer is about.  It would be better to move the selection only after the buffer is killed.

**Comment by clemera** [comment]
> the selection first moves foward and then back when I decide not to kill

Thanks, this is fixed by last commit.

**Comment by tmalsburg** [comment]
Awesome.  Thank you very much!  As far as I'm concerned, this issue can be closed.

**Comment by clemera** [comment]
Thanks for reaching out again, feel free to report any other suggestions that come up when using buffer-expose!
