### ISSUE TITLE
start the buffer-expose view with the hint letters?

### ISSUE THREAD

**Issue by zeltak** [clemera/buffer-expose#8]
hi again

really enjoying using Buffer-expose, thx so much for your hard work!

is there anyway to launch Buffer-expose with the little hint letter (like pressing SPACE) already on?

thx alot

Z

**Comment by clemera** [comment]
I added `buffer-expose-auto-init-aw` option (default nil). The display has a little lag don't know how to fix that).

**Comment by clemera** [comment]
If you press keys not displayed the fallback is to execute the binding for buffer-expose commands, so you can easily page to the next page. Just realized that the next page should auto start with ace window, as well. Will add that now.

**Comment by clemera** [comment]
Fixed, the lag is gone, too.

**Comment by zeltak** [comment]
thx a lot for adding this!

for some reason i dosent work for me (just updated)

this is my conf

```
(use-package buffer-expose  
 :ensure t
 :config
(buffer-expose-mode 1)
(setq buffer-expose-auto-init-aw t) 
 )
```

what am i missing?

best

Z

**Comment by clemera** [comment]
I'm not sure, your config seem legit. Could you provide more detail? What does it look like?

**Comment by clemera** [comment]
Does it work when you use Space?

**Comment by zeltak** [comment]
Hi
yeah it works when i manually press SPACE and then i see the hints. I just dont see the hints when i launch buffer-expose

best

z

**Comment by clemera** [comment]
If you use `C-h v buffer-expose-auto-init-aw RET` do you get the docstring? If not you are probably still load the older version. Maybe try to remove it and reinstall?

**Comment by clemera** [comment]
Any news on this?

**Comment by zeltak** [comment]
sorry real life got in the way :D 
here is what i get

```
buffer-expose-auto-init-aw's value is t


Documentation:

For more information check the manuals.

[back]
```

**Comment by clemera** [comment]
No problem, life is life ;) I still believe your are using an older version. If you jump to the source using the link in the help menu and go to buffer start what version does it show? It should be 0.4 if you are on the latest version. If not go to the ~/.emacs.d/elpa dir and remove the buffer-expose* folder. Than reinstall and see if it works.

**Comment by zeltak** [comment]
yup even though it said 0.4 deleting and reinstalling did the trick!

thx!

Z

**Comment by clemera** [comment]
Thanks!
