### ISSUE TITLE
Feature request - filter buffer-expose by file extension

### ISSUE THREAD

**Issue by xircon** [clemera/buffer-expose#9]
I am working on a bunch of python files, I only want to see them, similar to the buffer-expose-no-stars you kindly added for me :D

**Comment by clemera** [comment]
You could use something like the  following:

    (defun my-expose-python-buffers (&optional max)
      (interactive "P")
      (buffer-expose-show-buffers
       (buffer-list) max nil
       (lambda (buf)
         (eq 'python-mode
             (buffer-local-value 'major-mode buf)))))

**Comment by clemera** [comment]
You could use:

    (defun my-expose-python-buffers (&optional max)
      (interactive "P")
      (buffer-expose-major-mode max 'python-mode))

**Comment by xircon** [comment]
That works - thank you

**Comment by clemera** [comment]
You are welcome!
